export const FETCH_TODO_LIST_REQUEST = 'FETCH_TODO_LIST_REQUEST'
export const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS'
export const FETCH_TODO_LIST_FAILURE = 'FETCH_TODO_LIST_FAILURE'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED'

export const PERSIST_TODO_LIST_REQUEST = 'PERSIST_TODO_LIST_REQUEST'
export const PERSIST_TODO_LIST_SUCCESS = 'PERSIST_TODO_LIST_SUCCESS'
export const PERSIST_TODO_LIST_FAILED = 'PERSIST_TODO_LIST_FAILED'

export const TODO_STORAGE_KEY = 'TODOS'

export const DONE_TODO = 'DONE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const ADD_TODO_DRAFT = 'ADD_TODO_DRAFT'

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED'
